services:
  php-fpm:
    build: docker/php-fpm
    container_name: sendsay-php
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini'

  web:
    image: 'nginx:alpine'
    container_name: sendsay-nginx
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8089:80'
    depends_on:
      - php-fpm
